### PR TITLE
Pin ubuntu image to bionic, update README

### PR DESCRIPTION
**Pull request by jravetch**
Pin ubuntu image to bionic to avoid using focal, which breaks the build.  Update the README

### CODE REVIEW

**Comment by ouellettetech** [comment]
Only complaint is I would have labeled it as 18.04, since its easier to know what version that is, than bionic.

**Comment by jravetch** [comment]
@ouellettetech That's totally fair, hard to keep track of all the release names.  Updated to 18.04

**Review by ouellettetech — APPROVED** [review]

**Comment by jravetch** [comment]
I seem to not have write access so I can't merge @ouellettetech @greenbreakfast   Would either of you be able to grant me write access or better yet maintainer?

**Comment by ouellettetech** [comment]
Said the same for me... I'll ping Onion...

Sent from my T-Mobile 4G LTE Device

________________________________

**Comment by greenbreakfast** [comment]
@jravetch @ouellettetech looks like permissions changed recently, as far as I recall, you both should have had write access to both repos.
In any case, I've invited you both to a community-managers team in the ObooSmartClock organization. You'll have admin access to both repos.

**Comment by ouellettetech** [comment]
Thanks

Sent from my T-Mobile 4G LTE Device

________________________________

**Pull request merged**
